name: penguin_parking
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  uuid: ^4.4.2
  intl: ^0.19.0
  collection: ^1.19.0
  objectbox: ^4.0.3
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  lints: ^5.0.0
  # path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.13
  objectbox_generator: ^4.0.3
